# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: false

    serializer:
        default_context:
            # JSON_UNESCAPED_SLASHES (64) | JSON_PRETTY_PRINT (128) | JSON_UNESCAPED_UNICODE (256) - dotyczy m.in. odpowiedzi z błędami
            json_encode_options: 448

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
